# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2011-2020 ETH Zurich.

name: Verify the specified codebase

on:
  push: # run this workflow on every push
  pull_request: # run this workflow on every pull_request

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the VerifiedSCION repository
        uses: actions/checkout@v2
      - name: Cache the verification results
        uses: actions/cache@v3
        env:
          cache-name: gobra-cache
        with:
          path: ${{ runner.workspace }}/.gobra/cache.json
          key: ${{ env.cache-name }}
      - name: Verify the specified files
        uses: viperproject/gobra-action@verified-scion
        with:
          srcDirectory: gobra
          recursive: '1'
          globalTimeout: 5h
          packageTimeout: 4h
          viperBackend: VSWITHSILICON
          assumeInjectivityOnInhale: '1'
          caching: '1'
          # chopping is disabled for now to avoid cache misses.
          # this should be tested in a separate PR to figure if it
          # has an impact on verification times
          # chop: 10
      - name: Upload the verification report
        uses: actions/upload-artifact@v2
        with:
          name: verification_statistics
          path: ${{ runner.workspace }}/.gobra/stats.json
